/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        notion: {
          primary: "#5645d4",
          "primary-pressed": "#4534b3",
          "primary-deep": "#3a2a99",
          "brand-navy": "#0a1530",
          "brand-navy-deep": "#070f24",
          "brand-navy-mid": "#1a2a52",
          "link-blue": "#0075de",
          "brand-orange": "#dd5b00",
          "brand-pink": "#ff64c8",
          "brand-purple": "#7b3ff2",
          "brand-teal": "#2a9d99",
          "brand-green": "#1aae39",
          "brand-yellow": "#f5d75e",
          "brand-brown": "#523410",
          "card-peach": "#ffe8d4",
          "card-rose": "#fde0ec",
          "card-mint": "#d9f3e1",
          "card-lavender": "#e6e0f5",
          "card-sky": "#dcecfa",
          "card-yellow-bold": "#f9e79f",
          "card-cream": "#f8f5e8",
          "card-gray": "#f0eeec",
          canvas: "#ffffff",
          surface: "#f6f5f4",
          "surface-soft": "#fafaf9",
          hairline: "#e5e3df",
          "hairline-soft": "#ede9e4",
          "hairline-strong": "#c8c4be",
          "ink-deep": "#000000",
          ink: "#1a1a1a",
          charcoal: "#37352f",
          slate: "#5d5b54",
          steel: "#787671",
          stone: "#a4a097",
          muted: "#bbb8b1",
        },
        dark: {
          bg: "#0a1530",
          surface: "#0f1c3d",
          card: "#16254c",
          border: "#243769",
          hover: "#1d2e5a",
          text: "#f6f5f4",
          subtext: "#a4a097",
          muted: "#787671",
          selected: "#243769"
        },
        jira: {
          primary: "#5645d4",
          "primary-hover": "#4534b3",
          "primary-dark": "#3a2a99",
          "primary-light": "#e6e0f5",
          "primary-subtle": "#f6f5f4",
          bg: "#f6f5f4",
          surface: "#ffffff",
          sidebar: "#fafaf9",
          "sidebar-dark": "#0a1530",
          text: "#1a1a1a",
          subtext: "#5d5b54",
          muted: "#787671",
          border: "#e5e3df",
          "border-dark": "#c8c4be",
          hover: "#f0eeec",
          selected: "#e6e0f5",
          green: {
            DEFAULT: "#1aae39",
            bg: "#d9f3e1",
            text: "#006644",
          },
          yellow: {
            DEFAULT: "#dd5b00",
            bg: "#fef7d6",
            text: "#37352f",
          },
          red: {
            DEFAULT: "#e03131",
            bg: "#fde0ec",
            text: "#a02e6d",
          },
          purple: {
            DEFAULT: "#5645d4",
            bg: "#e6e0f5",
            text: "#391c57",
          },
          teal: {
            DEFAULT: "#2a9d99",
            bg: "#dcecfa",
            text: "#0075de",
          }
        }
      },
      borderRadius: {
        'md': '8px',
        'lg': '12px',
        'xl': '16px',
        '2xl': '20px',
        '3xl': '24px',
      },
      fontFamily: {
        sans: [
          "'Inter'",
          "'Notion Sans'",
          "-apple-system",
          "BlinkMacSystemFont",
          "'Segoe UI'",
          "'Roboto'",
          "sans-serif",
        ],
        mono: [
          "'SFMono-Medium'",
          "'SF Mono'",
          "'Segoe UI Mono'",
          "'Roboto Mono'",
          "'Fira Code'",
          "monospace",
        ]
      },
      boxShadow: {
        'notion-mockup': '0px 24px 48px -8px rgba(15, 15, 15, 0.20)',
        'notion-card': '0px 4px 12px 0px rgba(15, 15, 15, 0.08)',
        'notion-subtle': '0px 1px 2px 0px rgba(15, 15, 15, 0.04)',
        'notion-modal': '0px 16px 48px -8px rgba(15, 15, 15, 0.16)',
        jira: "0px 4px 12px 0px rgba(15, 15, 15, 0.08)",
        "jira-card": "0px 2px 6px 0px rgba(15, 15, 15, 0.05), 0 0 0 1px #e5e3df",
        "jira-modal": "0px 24px 48px -8px rgba(15, 15, 15, 0.25)",
        "jira-dropdown": "0px 12px 32px -4px rgba(15, 15, 15, 0.16), 0 0 0 1px #e5e3df"
      }
    },
  },
  plugins: [],
}
